pathBasis = '/Users/steve/Documents/MATLAB/osprey/fit/basissets/3T/philips/unedited/press/35/basis_philips_press35.mat';
includeMetabs = {'Asc','Asp','Cr','CrCH2' ...
                 ,'GABA','GPC','GSH','Gln','Glu' ...
                 ,'Ins','Lac','NAA','NAAG','PCh','PCr','PE' ...
                 ,'Scyllo','Tau'};
[out] = op_create_in_vivo_spec(pathBasis,includeMetabs,2000,2048);
figure(1), plot(out.ppm, real(out.specs));
set(gca, 'XDir', 'reverse', 'XLim', [0.5, 5], 'XMinorTick', 'On');